# Generated by Django 3.2.4 on 2021-06-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password1',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
