# Generated by Django 3.2.3 on 2021-06-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniprojectapp', '0003_auto_20210605_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_id',
            new_name='username',
        ),
    ]
