# Generated by Django 3.2.3 on 2021-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miniprojectapp', '0005_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mail_id', models.CharField(max_length=100)),
                ('password', models.CharField(default='None', max_length=20)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
