# Generated by Django 3.2.4 on 2021-06-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniprojectapp', '0006_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
